import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

/// A health-rule alert generated by the Rust rule engine and surfaced
/// to the UI via [HealthAlertService].
///
/// This type lives in the health bounded context and is not coupled
/// to the coaching subsystem.
class HealthAlert {
  const HealthAlert({
    required this.label,
    required this.message,
    required this.avgBpm,
    required this.windowMin,
  });

  /// Machine-readable label, e.g. `"sustained_low_hr"`.
  final String label;

  /// Human-readable alert message.
  final String message;

  /// Average BPM value parsed from the alert message.
  final int avgBpm;

  /// Window duration in minutes parsed from the alert message.
  final int windowMin;
}

/// Raw cue data received from the coaching stream and converted to a
/// health-domain type.
///
/// Used to bridge the coaching domain into the health domain without
/// exposing coaching types in the health API.
class RawCue {
  const RawCue({required this.label, required this.message});

  final String label;
  final String message;
}

/// Service that provides health-rule alerts (e.g. sustained low HR) to the UI
/// without coupling the screen to the coaching subsystem.
///
/// Receives raw cue data via an injected stream from [CoachingCueService],
/// avoiding a duplicate Rust stream subscription.
class HealthAlertService {
  HealthAlertService._();

  static final HealthAlertService _instance = HealthAlertService._();

  static HealthAlertService get instance => _instance;

  /// Stream of health alerts. Currently only emits for [sustained_low_hr],
  /// but this interface allows future health rules to be added without
  /// coupling additional coaching logic to the UI.
  Stream<HealthAlert> get healthAlertStream => _healthAlertController.stream;

  final StreamController<HealthAlert> _healthAlertController =
      StreamController<HealthAlert>.broadcast();

  /// Emits the current [HealthAlertState] whenever the health alert status changes.
  Stream<HealthAlertState> get healthAlertStateStream => _healthAlertStateController.stream;

  final StreamController<HealthAlertState> _healthAlertStateController =
      StreamController<HealthAlertState>.broadcast();

  /// The current health alert state.
  HealthAlertState get healthAlertState => _currentState;

  HealthAlertState _currentState = const HealthAlertState(HealthRuleStatus.ok, '');

  StreamSubscription<RawCue>? _cueSubscription;

  /// Start listening to the cue stream and filter for health alerts.
  /// Call this once at app startup, passing in the raw cue stream to listen on.
  ///
  /// The [cueStream] provides [RawCue] data extracted from [CoachingCueService].
  void startListening(Stream<RawCue> cueStream) {
    _cueSubscription?.cancel();
    _cueSubscription = cueStream.listen((cue) {
      if (cue.label == 'sustained_low_hr') {
        final avgBpm = _parseAvgBpm(cue.message);
        final windowMin = _parseWindowMin(cue.message);
        final alert = HealthAlert(
          label: cue.label,
          message: cue.message,
          avgBpm: avgBpm,
          windowMin: windowMin,
        );
        _healthAlertController.add(alert);
        _currentState = HealthAlertState(HealthRuleStatus.low, cue.message);
        _healthAlertStateController.add(_currentState);
      }
    });
    if (kDebugMode) {
      debugPrint('HealthAlertService: started listening to cue stream');
    }
  }

  /// Show a custom low-HR notification with the exact format required:
  /// title = 'Heart rate low', body = 'Average HR was {avg_bpm} bpm over
  /// the last {window_min} min', tap opens the Health screen.
  Future<void> showSustainedLowHrNotification(HealthAlert alert) async {
    const androidDetails = AndroidNotificationDetails(
      'health_alerts',
      'Health Alerts',
      channelDescription: 'Low heart rate health alerts',
      importance: Importance.high,
      priority: Priority.high,
      showWhen: true,
    );

    const iosDetails = DarwinNotificationDetails(
      presentAlert: true,
      presentBadge: true,
      presentSound: true,
    );

    const details = NotificationDetails(
      android: androidDetails,
      iOS: iosDetails,
    );

    const title = 'Heart rate low';
    final body = 'Average HR was ${alert.avgBpm} bpm over the last ${alert.windowMin} min';

    await _notificationPlugin.show(
      alert.hashCode,
      title,
      body,
      details,
      payload: 'sustained_low_hr',
    );

    if (kDebugMode) {
      debugPrint('HealthAlertService: showed low-HR notification: $body');
    }
  }

  final FlutterLocalNotificationsPlugin _notificationPlugin =
      FlutterLocalNotificationsPlugin();

  /// Clean up resources. Call when the service is no longer needed.
  void dispose() {
    _cueSubscription?.cancel();
    _cueSubscription = null;
    _healthAlertController.close();
    _healthAlertStateController.close();
  }

  int _parseAvgBpm(String message) {
    final match = RegExp(r'(\d+) bpm').firstMatch(message);
    return int.tryParse(match?.group(1) ?? '0') ?? 0;
  }

  int _parseWindowMin(String message) {
    final match = RegExp(r'last ([\d.]+) min').firstMatch(message);
    if (match == null) return 0;
    return double.parse(match.group(1)!).round();
  }
}

/// Immutable health alert state containing the current rule status and detail message.
class HealthAlertState {
  final HealthRuleStatus status;
  final String detail;

  const HealthAlertState(this.status, this.detail);
}

/// Health rule status enum.
enum HealthRuleStatus { ok, low }