// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'domain/heart_rate.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `create_session_progress_forwarder`, `get_battery_stream_receiver`, `get_ble_adapter`, `get_connection_status_receiver`, `get_data_dir`, `get_hr_store`, `get_hr_stream_receiver`, `get_or_create_battery_broadcast_sender`, `get_or_create_coaching_cue_broadcast_sender`, `get_or_create_connection_status_broadcast_sender`, `get_or_create_hr_broadcast_sender`, `get_or_create_session_progress_broadcast_sender`, `get_session_executor`, `get_session_progress_receiver`, `get_session_repository`, `load_plan`, `save_plan`, `subscribe_coaching_cue_stream`, `zone_from_number`, `zone_to_number`
// These functions are ignored because they have generic arguments: `notify`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ConnectionState`, `FlutterLogWriter`, `StubNotificationPort`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `flush`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `make_writer`, `write`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `emit_cue`, `subscribe_connection_status_stream`, `subscribe_hr_stream`, `subscribe_session_progress_stream`

/// Initialize the panic handler for FFI safety.
///
/// This function sets up a panic hook that catches Rust panics and logs them
/// using the tracing framework instead of crashing the app. This is critical
/// for Android/iOS where uncaught panics would terminate the entire application.
///
/// **IMPORTANT**: This function should be called once during Flutter app initialization,
/// before making any other FFI calls to Rust.
///
/// # Examples
///
/// In your Flutter/Dart code:
/// ```dart
/// void main() async {
///   // Initialize Rust panic handler first
///   await RustLib.init();
///   initPanicHandler();
///
///   runApp(MyApp());
/// }
/// ```
Future<void> initPanicHandler() =>
    RustLib.instance.api.crateApiInitPanicHandler();

/// Initialize platform-specific BLE requirements.
///
/// This function performs platform-specific initialization required for BLE operations.
/// On Android, btleplug requires JNI environment initialization before any BLE operations
/// can be performed. On other platforms (Linux, macOS, Windows, iOS), this is a no-op.
///
/// **IMPORTANT**: This function should be called once during Flutter app initialization,
/// after RustLib.init() but before making any BLE API calls (scan_devices, connect_device, etc.).
///
/// # Returns
///
/// Returns Ok(()) if initialization succeeds, or an error if platform-specific setup fails.
///
/// # Errors
///
/// On Android: Returns an error if btleplug platform initialization fails (e.g., missing
/// Bluetooth permissions, BLE hardware unavailable).
///
/// # Examples
///
/// In your Flutter/Dart code:
/// ```dart
/// void main() async {
///   await RustLib.init();
///   await initPlatform(); // Initialize BLE platform
///
///   runApp(MyApp());
/// }
/// ```
Future<void> initPlatform() => RustLib.instance.api.crateApiInitPlatform();

/// Initialize the coaching rule engine.
///
/// This sets up the rule engine with default rules (target zone, inactivity,
/// overwork) and starts it evaluating HR samples as they arrive via the
/// `emit_hr_data` path in `connect_device` and `start_mock_mode`.
///
/// # Examples
///
/// ```dart
/// await initCoachingEngine();
/// ```
Future<void> initCoachingEngine() =>
    RustLib.instance.api.crateApiInitCoachingEngine();

/// Update the LowHrRule with the user's health settings.
///
/// Called from Dart whenever the user changes threshold, sustained window,
/// quiet hours, or notification preferences in HealthSettingsScreen.
/// The rule is updated immediately so the next tick (≤30s) uses new values.
Future<void> updateHealthSettings({
  required int thresholdBpm,
  required BigInt sustainedSecs,
  required int quietStartHour,
  required int quietEndHour,
  required bool notificationsEnabled,
}) => RustLib.instance.api.crateApiUpdateHealthSettings(
  thresholdBpm: thresholdBpm,
  sustainedSecs: sustainedSecs,
  quietStartHour: quietStartHour,
  quietEndHour: quietEndHour,
  notificationsEnabled: notificationsEnabled,
);

/// Initialize logging and forward Rust tracing logs to Flutter.
///
/// This function sets up a tracing subscriber that captures all Rust log messages
/// (at the level specified by the RUST_LOG environment variable) and forwards them
/// to Flutter via a StreamSink. This enables unified logging for debugging where
/// both Dart and Rust logs can be viewed together.
///
/// **IMPORTANT**: This function should be called once during Flutter app initialization,
/// after RustLib.init() but before making any other FFI calls that generate logs.
///
/// # Arguments
///
/// * `sink` - The FRB StreamSink that will receive log messages
///
/// # Environment Variables
///
/// * `RUST_LOG` - Controls the log level (TRACE, DEBUG, INFO, WARN, ERROR).
///   Defaults to INFO if not set. Example: `RUST_LOG=debug` or `RUST_LOG=heart_beat=trace`
///
/// # Examples
///
/// In your Flutter/Dart code:
/// ```dart
/// void main() async {
///   await RustLib.init();
///
///   // Create a stream to receive logs
///   final logStream = StreamController<LogMessage>();
///   initLogging(sink: logStream.sink);
///
///   // Listen to logs
///   logStream.stream.listen((log) {
///     debugPrint('[${log.level}] ${log.target}: ${log.message}');
///   });
///
///   runApp(MyApp());
/// }
/// ```
Stream<LogMessage> initLogging() => RustLib.instance.api.crateApiInitLogging();

/// Set the base data directory for storing app data.
///
/// On Android, this must be called during app initialization before using any
/// file-based APIs (list_plans, start_workout, list_sessions, etc.). The path
/// should be the app's documents directory obtained from Flutter's path_provider.
///
/// On desktop platforms (Linux, macOS, Windows), this is optional - if not set,
/// the APIs will fall back to using ~/.heart-beat as the data directory.
///
/// # Arguments
///
/// * `path` - Absolute path to the app's data directory
///
/// # Examples
///
/// In your Flutter/Dart code:
/// ```dart
/// import 'package:path_provider/path_provider.dart';
///
/// void main() async {
///   await RustLib.init();
///
///   // Set data directory for file storage
///   final appDir = await getApplicationDocumentsDirectory();
///   await setDataDir(path: appDir.path);
///
///   runApp(MyApp());
/// }
/// ```
Future<void> setDataDir({required String path}) =>
    RustLib.instance.api.crateApiSetDataDir(path: path);

/// Start the debug HTTP server on the given port.
///
/// In debug builds this spawns an axum server on `0.0.0.0:<port>` serving the
/// debug REST API and WebSocket endpoints. In release builds this is a no-op.
///
/// The server is idempotent — calling this multiple times has no additional
/// effect if a server is already running. On port binding failure, logs a
/// warning and returns `Ok` without blocking app startup.
///
/// # Arguments
///
/// * `port` - The TCP port to listen on (default 8888)
///
/// # Example
///
/// ```dart
/// if (kDebugMode) {
///   await startDebugServer(port: 8888);
/// }
/// ```
Future<void> startDebugServer({required int port}) =>
    RustLib.instance.api.crateApiStartDebugServer(port: port);

/// Scan for BLE heart rate devices.
///
/// Initiates a BLE scan and returns all discovered devices advertising
/// the Heart Rate Service (UUID 0x180D).
///
/// # Returns
///
/// A list of discovered devices with their IDs, names, and signal strength.
///
/// # Errors
///
/// Returns an error if:
/// - BLE adapter initialization fails
/// - Scan operation fails
/// - BLE is not available or permissions are missing
Future<List<DiscoveredDevice>> scanDevices() =>
    RustLib.instance.api.crateApiScanDevices();

/// Connect to a BLE heart rate device.
///
/// Establishes a connection to the specified device and transitions the
/// connectivity state machine to the Connected state.
///
/// # Arguments
///
/// * `device_id` - Platform-specific device identifier from scan results
///
/// # Errors
///
/// Returns an error if:
/// - Device is not found
/// - Connection fails
/// - Connection timeout (15 seconds)
Future<void> connectDevice({required String deviceId}) =>
    RustLib.instance.api.crateApiConnectDevice(deviceId: deviceId);

/// Disconnect from the currently connected device.
///
/// Gracefully disconnects from the active BLE connection and transitions
/// the state machine back to Idle. This function aborts background tasks
/// (HR streaming and battery polling) and cleanly disconnects the BLE adapter.
///
/// This function is idempotent - calling it when already disconnected is safe
/// and will succeed without error.
///
/// # Errors
///
/// Returns an error if the BLE adapter fails to disconnect.
Future<void> disconnect() => RustLib.instance.api.crateApiDisconnect();

/// Start mock mode for testing without hardware.
///
/// Creates a MockAdapter, connects to a simulated device, and spawns a
/// background task that periodically emits mock HR data via the broadcast
/// channels. Also emits connection status and battery updates.
Future<void> startMockMode() => RustLib.instance.api.crateApiStartMockMode();

/// Create a stream for receiving filtered heart rate data.
///
/// Sets up a stream that will receive real-time filtered heart rate measurements
/// from the filtering pipeline. This function is used by Flutter via FRB to
/// create a reactive data stream.
///
/// # Arguments
///
/// * `sink` - The FRB StreamSink that will receive the HR data
///
/// # Returns
///
/// Returns Ok(()) if the stream was successfully set up.
Stream<ApiFilteredHeartRate> createHrStream() =>
    RustLib.instance.api.crateApiCreateHrStream();

/// Emit filtered heart rate data to all stream subscribers.
///
/// This function should be called by the filtering pipeline when new filtered
/// HR data is available. It broadcasts the data to all active stream subscribers.
///
/// # Arguments
///
/// * `data` - The filtered heart rate measurement to broadcast
///
/// # Returns
///
/// The number of receivers that received the data. Returns 0 if no receivers
/// are currently subscribed.
///
/// # Example
///
/// ```rust,ignore
/// // In your filtering pipeline:
/// let filtered_data = FilteredHeartRate { /* ... */ };
/// emit_hr_data(filtered_data);
/// ```
Future<BigInt> emitHrData({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiEmitHrData(data: data);

/// Get the raw (unfiltered) BPM value from filtered heart rate data
Future<int> hrRawBpm({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrRawBpm(data: data);

/// Get the filtered BPM value from filtered heart rate data
Future<int> hrFilteredBpm({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrFilteredBpm(data: data);

/// Get the RMSSD heart rate variability metric in milliseconds
Future<double?> hrRmssd({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrRmssd(data: data);

/// Get the filter variance (confidence indicator) in BPM²
///
/// The variance represents the Kalman filter's estimated uncertainty:
/// - < 1.0: High confidence (filter has converged)
/// - 1.0-5.0: Moderate confidence (filter is stable)
/// - > 5.0: Low confidence (filter is warming up or tracking changes)
Future<double?> hrFilterVariance({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrFilterVariance(data: data);

/// Get the battery level as a percentage (0-100)
Future<int?> hrBatteryLevel({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrBatteryLevel(data: data);

/// Get the timestamp in milliseconds since Unix epoch
Future<BigInt> hrTimestamp({required ApiFilteredHeartRate data}) =>
    RustLib.instance.api.crateApiHrTimestamp(data: data);

/// Get the high-precision receive timestamp in microseconds since Unix epoch
///
/// This timestamp is captured immediately when the BLE notification is received,
/// using a monotonic clock for accuracy. It can be used by the UI layer to
/// calculate end-to-end latency from BLE event to UI update.
///
/// Returns `None` if timestamp capture was not available or not enabled.
Future<BigInt?> hrReceiveTimestampMicros({
  required ApiFilteredHeartRate data,
}) => RustLib.instance.api.crateApiHrReceiveTimestampMicros(data: data);

/// Calculate the heart rate zone based on a maximum heart rate
///
/// # Arguments
///
/// * `data` - The filtered heart rate data
/// * `max_hr` - The user's maximum heart rate
///
/// # Returns
///
/// The training zone (Zone1-Zone5) based on percentage of max HR
Future<Zone> hrZone({required ApiFilteredHeartRate data, required int maxHr}) =>
    RustLib.instance.api.crateApiHrZone(data: data, maxHr: maxHr);

/// Create a dummy battery level for testing (temporary helper for FRB codegen).
///
/// This function helps FRB discover the ApiBatteryLevel type during code generation.
/// TODO: Remove this after ApiBatteryLevel is properly integrated.
Future<ApiBatteryLevel> dummyBatteryLevelForCodegen() =>
    RustLib.instance.api.crateApiDummyBatteryLevelForCodegen();

/// Create a dummy connection status for testing (temporary helper for FRB codegen).
///
/// This function helps FRB discover the ApiConnectionStatus type during code generation.
Future<ApiConnectionStatus> dummyConnectionStatusForCodegen() =>
    RustLib.instance.api.crateApiDummyConnectionStatusForCodegen();

/// Create a stream for receiving battery level data.
///
/// Sets up a stream that will receive real-time battery level measurements
/// from the connected BLE device. This function is used by Flutter via FRB to
/// create a reactive data stream.
///
/// # Arguments
///
/// * `sink` - The FRB StreamSink that will receive the battery data
///
/// # Returns
///
/// Returns Ok(()) if the stream was successfully set up.
Stream<ApiBatteryLevel> createBatteryStream() =>
    RustLib.instance.api.crateApiCreateBatteryStream();

/// Subscribe to the real-time battery level stream.
Future<ReceiverApiBatteryLevel> subscribeBatteryStream() =>
    RustLib.instance.api.crateApiSubscribeBatteryStream();

/// Emit battery level data to all stream subscribers.
///
/// This function should be called by the battery polling task when new battery
/// data is available. It broadcasts the data to all active stream subscribers.
///
/// # Arguments
///
/// * `data` - The battery level measurement to broadcast
///
/// # Returns
///
/// The number of receivers that received the data. Returns 0 if no receivers
/// are currently subscribed.
///
/// # Example
///
/// ```rust,ignore
/// // In your battery polling task:
/// let battery_data = BatteryLevel { /* ... */ };
/// emit_battery_data(battery_data);
/// ```
Future<BigInt> emitBatteryData({required ApiBatteryLevel data}) =>
    RustLib.instance.api.crateApiEmitBatteryData(data: data);

/// Create a stream of session progress updates during workout execution.
///
/// This stream emits SessionProgress updates at regular intervals (typically 1Hz)
/// while a workout is running, providing real-time feedback on phase progress,
/// zone status, and elapsed/remaining time.
///
/// # Arguments
///
/// * `sink` - The FRB StreamSink that will receive the session progress data
///
/// # Returns
///
/// Returns Ok(()) if the stream was successfully set up.
///
/// # Example
///
/// ```dart
/// // In Flutter:
/// final stream = await api.createSessionProgressStream();
/// stream.listen((progress) {
///   print('Current phase: ${progress.phaseProgress.phaseName}');
///   print('Zone status: ${progress.zoneStatus}');
/// });
/// ```
Stream<ApiSessionProgress> createSessionProgressStream() =>
    RustLib.instance.api.crateApiCreateSessionProgressStream();

/// Emit session progress data to all stream subscribers.
///
/// This function is called by the SessionExecutor tick loop when progress updates
/// are available. It broadcasts the data to all active stream subscribers.
///
/// # Arguments
///
/// * `data` - The session progress snapshot to broadcast
///
/// # Returns
///
/// The number of receivers that received the data. Returns 0 if no receivers
/// are currently subscribed.
Future<BigInt> emitSessionProgress({required ApiSessionProgress data}) =>
    RustLib.instance.api.crateApiEmitSessionProgress(data: data);

/// Create a stream for receiving connection status updates.
///
/// Sets up a stream that will receive real-time connection status updates
/// during BLE device connection, reconnection attempts, and failures.
/// This function is used by Flutter via FRB to create a reactive data stream.
///
/// # Arguments
///
/// * `sink` - The FRB StreamSink that will receive the connection status data
///
/// # Returns
///
/// Returns Ok(()) if the stream was successfully set up.
///
/// # Example
///
/// ```dart
/// // In Flutter:
/// final stream = await api.createConnectionStatusStream();
/// stream.listen((status) {
///   if (status.type == 'reconnecting') {
///     print('Reconnecting... attempt ${status.attempt}/${status.max_attempts}');
///   } else if (status.type == 'connected') {
///     print('Connected to ${status.device_id}');
///   }
/// });
/// ```
Stream<ApiConnectionStatus> createConnectionStatusStream() =>
    RustLib.instance.api.crateApiCreateConnectionStatusStream();

/// Emit connection status data to all stream subscribers.
///
/// This function should be called by the BLE adapter when connection status changes.
/// It broadcasts the status to all active stream subscribers.
///
/// # Arguments
///
/// * `status` - The connection status to broadcast
///
/// # Returns
///
/// The number of receivers that received the status. Returns 0 if no receivers
/// are currently subscribed.
///
/// # Example
///
/// ```rust,ignore
/// // When starting reconnection:
/// emit_connection_status(ConnectionStatus::Reconnecting { attempt: 1, max_attempts: 5 });
///
/// // When connected:
/// emit_connection_status(ConnectionStatus::Connected { device_id: "AA:BB:CC:DD:EE:FF".to_string() });
///
/// // When reconnection fails:
/// emit_connection_status(ConnectionStatus::ReconnectFailed { reason: "Max attempts exceeded".to_string() });
/// ```
Future<BigInt> emitConnectionStatus({required ApiConnectionStatus status}) =>
    RustLib.instance.api.crateApiEmitConnectionStatus(status: status);

/// Emit a coaching cue to all stream subscribers.
///
/// Called by the coaching rule engine when a cue should be delivered to the user.
Future<BigInt> emitCoachingCue({required ApiCue cue}) =>
    RustLib.instance.api.crateApiEmitCoachingCue(cue: cue);

/// Create a stream for receiving coaching cues.
Stream<ApiCue> createCoachingCueStream() =>
    RustLib.instance.api.crateApiCreateCoachingCueStream();

/// Check if the connection status is Disconnected.
Future<bool> connectionStatusIsDisconnected({
  required ApiConnectionStatus status,
}) =>
    RustLib.instance.api.crateApiConnectionStatusIsDisconnected(status: status);

/// Check if the connection status is Connecting.
Future<bool> connectionStatusIsConnecting({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusIsConnecting(status: status);

/// Check if the connection status is Connected.
Future<bool> connectionStatusIsConnected({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusIsConnected(status: status);

/// Check if the connection status is Reconnecting.
Future<bool> connectionStatusIsReconnecting({
  required ApiConnectionStatus status,
}) =>
    RustLib.instance.api.crateApiConnectionStatusIsReconnecting(status: status);

/// Check if the connection status is ReconnectFailed.
Future<bool> connectionStatusIsReconnectFailed({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusIsReconnectFailed(
  status: status,
);

/// Get the device ID from a Connected status.
/// Returns None if the status is not Connected.
Future<String?> connectionStatusDeviceId({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusDeviceId(status: status);

/// Get the current attempt number from a Reconnecting status.
/// Returns None if the status is not Reconnecting.
Future<int?> connectionStatusAttempt({required ApiConnectionStatus status}) =>
    RustLib.instance.api.crateApiConnectionStatusAttempt(status: status);

/// Get the max attempts from a Reconnecting status.
/// Returns None if the status is not Reconnecting.
Future<int?> connectionStatusMaxAttempts({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusMaxAttempts(status: status);

/// Get the failure reason from a ReconnectFailed status.
/// Returns None if the status is not ReconnectFailed.
Future<String?> connectionStatusFailureReason({
  required ApiConnectionStatus status,
}) =>
    RustLib.instance.api.crateApiConnectionStatusFailureReason(status: status);

/// Convert connection status to a human-readable string.
Future<String> connectionStatusToString({
  required ApiConnectionStatus status,
}) => RustLib.instance.api.crateApiConnectionStatusToString(status: status);

/// Returns all HR samples with timestamps in [start_ms, end_ms] across all daily files.
/// Samples are returned in chronological order.
Future<List<ApiSample>> samplesInRange({
  required BigInt startMs,
  required BigInt endMs,
}) =>
    RustLib.instance.api.crateApiSamplesInRange(startMs: startMs, endMs: endMs);

/// Computes the rolling average BPM over the given window (in seconds) ending at the latest sample.
/// Returns `None` if the store is empty or no samples fall within the window.
Future<double?> rollingAvg({required BigInt windowSecs}) =>
    RustLib.instance.api.crateApiRollingAvg(windowSecs: windowSecs);

/// Returns the most recent HR sample, or `None` if the store is empty.
Future<ApiSample?> latestSample() =>
    RustLib.instance.api.crateApiLatestSample();

/// Returns the BPM of an HR sample.
Future<int> apiSampleBpm({required ApiSample sample}) =>
    RustLib.instance.api.crateApiApiSampleBpm(sample: sample);

/// Returns the Unix timestamp in milliseconds of an HR sample.
Future<BigInt> apiSampleTsMs({required ApiSample sample}) =>
    RustLib.instance.api.crateApiApiSampleTsMs(sample: sample);

/// Returns BPM and timestamp for multiple samples in a single call.
///
/// Useful for resolving sparkline data without making individual FFI calls per sample.
Future<List<(int, BigInt)>> samplesBpmAndTs({
  required List<ApiSample> samples,
}) => RustLib.instance.api.crateApiSamplesBpmAndTs(samples: samples);

/// List all completed training sessions.
///
/// Returns a list of session summaries sorted by start time (most recent first).
/// This is optimized for displaying in a list view - full session data is not loaded.
///
/// # Returns
///
/// A vector of session summary previews containing ID, plan name, start time,
/// duration, average heart rate, and status.
///
/// # Errors
///
/// Returns an error if the sessions directory cannot be read or if the repository
/// cannot be initialized.
Future<List<ApiSessionSummaryPreview>> listSessions() =>
    RustLib.instance.api.crateApiListSessions();

/// Get a complete session by its ID.
///
/// Loads the full session data including all heart rate samples and statistics.
/// This is intended for displaying detailed session information.
///
/// # Arguments
///
/// * `id` - The unique identifier of the session to retrieve
///
/// # Returns
///
/// The complete session if found, or `None` if no session with the given ID exists.
///
/// # Errors
///
/// Returns an error if the session file cannot be read or parsed, or if the
/// repository cannot be initialized.
Future<ApiCompletedSession?> getSession({required String id}) =>
    RustLib.instance.api.crateApiGetSession(id: id);

/// Delete a session by its ID.
///
/// Permanently removes the session and all its data from storage.
///
/// # Arguments
///
/// * `id` - The unique identifier of the session to delete
///
/// # Errors
///
/// Returns an error if the session file cannot be deleted or if the repository
/// cannot be initialized. Succeeds silently if the session doesn't exist.
Future<void> deleteSession({required String id}) =>
    RustLib.instance.api.crateApiDeleteSession(id: id);

/// Export a session to a specified format.
///
/// Loads a completed session and exports it in the requested format (CSV, JSON, or text summary).
/// The returned string can be saved to a file or shared directly.
///
/// # Arguments
///
/// * `id` - The unique identifier of the session to export
/// * `format` - The desired export format (Csv, Json, or Summary)
///
/// # Returns
///
/// A string containing the exported session data in the requested format.
///
/// # Errors
///
/// Returns an error if:
/// - The session cannot be found
/// - The session repository cannot be initialized
/// - The session data cannot be formatted (should not normally occur)
///
/// # Examples
///
/// ```no_run
/// # use heart_beat::api::{export_session, ExportFormat};
/// # tokio::runtime::Runtime::new().unwrap().block_on(async {
/// let csv_data = export_session("session-123".to_string(), ExportFormat::Csv).await?;
/// let json_data = export_session("session-123".to_string(), ExportFormat::Json).await?;
/// let summary = export_session("session-123".to_string(), ExportFormat::Summary).await?;
/// # Ok::<(), anyhow::Error>(())
/// # });
/// ```
Future<String> exportSession({
  required String id,
  required ExportFormat format,
}) => RustLib.instance.api.crateApiExportSession(id: id, format: format);

/// Get the session ID from a session summary preview
Future<String> sessionPreviewId({required ApiSessionSummaryPreview preview}) =>
    RustLib.instance.api.crateApiSessionPreviewId(preview: preview);

/// Get the plan name from a session summary preview
Future<String> sessionPreviewPlanName({
  required ApiSessionSummaryPreview preview,
}) => RustLib.instance.api.crateApiSessionPreviewPlanName(preview: preview);

/// Get the start time as Unix timestamp in milliseconds from a session summary preview
Future<PlatformInt64> sessionPreviewStartTime({
  required ApiSessionSummaryPreview preview,
}) => RustLib.instance.api.crateApiSessionPreviewStartTime(preview: preview);

/// Get the duration in seconds from a session summary preview
Future<int> sessionPreviewDurationSecs({
  required ApiSessionSummaryPreview preview,
}) => RustLib.instance.api.crateApiSessionPreviewDurationSecs(preview: preview);

/// Get the average heart rate from a session summary preview
Future<int> sessionPreviewAvgHr({required ApiSessionSummaryPreview preview}) =>
    RustLib.instance.api.crateApiSessionPreviewAvgHr(preview: preview);

/// Get the status string from a session summary preview
Future<String> sessionPreviewStatus({
  required ApiSessionSummaryPreview preview,
}) => RustLib.instance.api.crateApiSessionPreviewStatus(preview: preview);

/// Get the session ID from a completed session
Future<String> sessionId({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionId(session: session);

/// Get the plan name from a completed session
Future<String> sessionPlanName({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionPlanName(session: session);

/// Get the start time as Unix timestamp in milliseconds from a completed session
Future<PlatformInt64> sessionStartTime({
  required ApiCompletedSession session,
}) => RustLib.instance.api.crateApiSessionStartTime(session: session);

/// Get the end time as Unix timestamp in milliseconds from a completed session
Future<PlatformInt64> sessionEndTime({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionEndTime(session: session);

/// Get the status string from a completed session
Future<String> sessionStatus({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionStatus(session: session);

/// Get the number of phases completed from a completed session
Future<int> sessionPhasesCompleted({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionPhasesCompleted(session: session);

/// Get the duration in seconds from a completed session summary
Future<int> sessionSummaryDurationSecs({
  required ApiCompletedSession session,
}) => RustLib.instance.api.crateApiSessionSummaryDurationSecs(session: session);

/// Get the average heart rate from a completed session summary
Future<int> sessionSummaryAvgHr({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionSummaryAvgHr(session: session);

/// Get the maximum heart rate from a completed session summary
Future<int> sessionSummaryMaxHr({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionSummaryMaxHr(session: session);

/// Get the minimum heart rate from a completed session summary
Future<int> sessionSummaryMinHr({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionSummaryMinHr(session: session);

/// Get the time in zone array from a completed session summary
/// Returns an array of 5 elements representing time spent in each zone (Zone1-Zone5) in seconds
Future<Uint32List> sessionSummaryTimeInZone({
  required ApiCompletedSession session,
}) => RustLib.instance.api.crateApiSessionSummaryTimeInZone(session: session);

/// Get the number of heart rate samples in a completed session
Future<BigInt> sessionHrSamplesCount({required ApiCompletedSession session}) =>
    RustLib.instance.api.crateApiSessionHrSamplesCount(session: session);

/// Get a specific heart rate sample from a completed session
/// Returns a tuple of (timestamp_millis, bpm)
Future<(PlatformInt64, int)?> sessionHrSampleAt({
  required ApiCompletedSession session,
  required BigInt index,
}) => RustLib.instance.api.crateApiSessionHrSampleAt(
  session: session,
  index: index,
);

/// Get all heart rate samples from a completed session in a single call.
/// Returns a vector of tuples of (timestamp_millis, bpm) in chronological order.
Future<List<(PlatformInt64, int)>> sessionHrSamples({
  required ApiCompletedSession session,
}) => RustLib.instance.api.crateApiSessionHrSamples(session: session);

/// List all available training plans.
///
/// Returns a list of plan names from the data directory's plans/ subdirectory.
/// Each plan is stored as a JSON file named `{plan_name}.json`.
///
/// # Returns
///
/// A vector of plan name strings. Returns an empty vector if no plans are found
/// or if the plans directory doesn't exist yet.
///
/// # Errors
///
/// Returns an error if the data directory cannot be determined or if there are
/// issues reading the plans directory.
Future<List<String>> listPlans() => RustLib.instance.api.crateApiListPlans();

/// Seed default training plans if none exist.
///
/// Creates a set of sample training plans for users to get started with.
/// This function is idempotent - it only creates plans if the plans directory
/// is empty or doesn't exist.
///
/// # Default Plans Created
///
/// - **Easy Run** (30 min): 10min Zone2 warmup, 10min Zone2 main, 10min Zone1 cooldown
/// - **Tempo Run** (40 min): 10min Zone2 warmup, 20min Zone3 tempo, 10min Zone1 cooldown
/// - **Interval Training** (35 min): Warmup + 5x(3min Zone4 / 2min Zone2) + Cooldown
/// - **Long Slow Distance** (60 min): Steady Zone2 aerobic base building
/// - **Recovery Run** (20 min): Easy Zone1 active recovery
///
/// # Returns
///
/// The number of plans created. Returns 0 if plans already exist.
Future<int> seedDefaultPlans() =>
    RustLib.instance.api.crateApiSeedDefaultPlans();

/// Start a workout session with the specified training plan.
///
/// Loads the plan from ~/.heart-beat/plans/{plan_name}.json and starts
/// executing it. The session will emit progress updates via the progress stream
/// and save the completed session to the repository.
///
/// # Arguments
///
/// * `plan_name` - The name of the training plan to execute (without .json extension)
///
/// # Returns
///
/// Returns Ok(()) if the workout started successfully.
///
/// # Errors
///
/// Returns an error if:
/// - The plan file cannot be found or loaded
/// - A workout is already in progress
/// - The executor cannot be initialized
Future<void> startWorkout({required String planName}) =>
    RustLib.instance.api.crateApiStartWorkout(planName: planName);

/// Pause the currently running workout.
///
/// The workout timer stops but the session state is preserved.
/// Call `resume_workout()` to continue from where you left off.
///
/// # Errors
///
/// Returns an error if no workout is currently running or if the executor
/// is not initialized.
Future<void> pauseWorkout() => RustLib.instance.api.crateApiPauseWorkout();

/// Resume a paused workout.
///
/// Continues the workout from where it was paused. The timer resumes
/// counting and progress updates continue.
///
/// # Errors
///
/// Returns an error if no workout is paused or if the executor is not initialized.
Future<void> resumeWorkout() => RustLib.instance.api.crateApiResumeWorkout();

/// Stop the currently running workout.
///
/// Ends the workout and saves the session to the repository. The session
/// will be marked as "Stopped" rather than "Completed".
///
/// # Errors
///
/// Returns an error if no workout is running or if the executor is not initialized.
Future<void> stopWorkout() => RustLib.instance.api.crateApiStopWorkout();

/// Get the current session state from SessionProgress.
Future<ApiSessionState> sessionProgressState({
  required ApiSessionProgress progress,
}) => RustLib.instance.api.crateApiSessionProgressState(progress: progress);

/// Get the current phase index from SessionProgress.
Future<int> sessionProgressCurrentPhase({
  required ApiSessionProgress progress,
}) => RustLib.instance.api.crateApiSessionProgressCurrentPhase(
  progress: progress,
);

/// Get the total elapsed seconds from SessionProgress.
Future<int> sessionProgressTotalElapsedSecs({
  required ApiSessionProgress progress,
}) => RustLib.instance.api.crateApiSessionProgressTotalElapsedSecs(
  progress: progress,
);

/// Get the total remaining seconds from SessionProgress.
Future<int> sessionProgressTotalRemainingSecs({
  required ApiSessionProgress progress,
}) => RustLib.instance.api.crateApiSessionProgressTotalRemainingSecs(
  progress: progress,
);

/// Get the zone status from SessionProgress.
Future<ApiZoneStatus> sessionProgressZoneStatus({
  required ApiSessionProgress progress,
}) =>
    RustLib.instance.api.crateApiSessionProgressZoneStatus(progress: progress);

/// Get the current BPM from SessionProgress.
Future<int> sessionProgressCurrentBpm({required ApiSessionProgress progress}) =>
    RustLib.instance.api.crateApiSessionProgressCurrentBpm(progress: progress);

/// Get the phase progress from SessionProgress.
Future<ApiPhaseProgress> sessionProgressPhaseProgress({
  required ApiSessionProgress progress,
}) => RustLib.instance.api.crateApiSessionProgressPhaseProgress(
  progress: progress,
);

/// Get the phase index from PhaseProgress.
Future<int> phaseProgressPhaseIndex({required ApiPhaseProgress progress}) =>
    RustLib.instance.api.crateApiPhaseProgressPhaseIndex(progress: progress);

/// Get the phase name from PhaseProgress.
Future<String> phaseProgressPhaseName({required ApiPhaseProgress progress}) =>
    RustLib.instance.api.crateApiPhaseProgressPhaseName(progress: progress);

/// Get the target zone from PhaseProgress.
Future<Zone> phaseProgressTargetZone({required ApiPhaseProgress progress}) =>
    RustLib.instance.api.crateApiPhaseProgressTargetZone(progress: progress);

/// Get the elapsed seconds in the current phase from PhaseProgress.
Future<int> phaseProgressElapsedSecs({required ApiPhaseProgress progress}) =>
    RustLib.instance.api.crateApiPhaseProgressElapsedSecs(progress: progress);

/// Get the remaining seconds in the current phase from PhaseProgress.
Future<int> phaseProgressRemainingSecs({required ApiPhaseProgress progress}) =>
    RustLib.instance.api.crateApiPhaseProgressRemainingSecs(progress: progress);

/// Check if the session state is Running.
Future<bool> sessionStateIsRunning({required ApiSessionState state}) =>
    RustLib.instance.api.crateApiSessionStateIsRunning(state: state);

/// Check if the session state is Paused.
Future<bool> sessionStateIsPaused({required ApiSessionState state}) =>
    RustLib.instance.api.crateApiSessionStateIsPaused(state: state);

/// Check if the session state is Completed.
Future<bool> sessionStateIsCompleted({required ApiSessionState state}) =>
    RustLib.instance.api.crateApiSessionStateIsCompleted(state: state);

/// Check if the session state is Stopped.
Future<bool> sessionStateIsStopped({required ApiSessionState state}) =>
    RustLib.instance.api.crateApiSessionStateIsStopped(state: state);

/// Convert SessionState to a string representation.
Future<String> sessionStateToString({required ApiSessionState state}) =>
    RustLib.instance.api.crateApiSessionStateToString(state: state);

/// Check if the zone status is InZone.
Future<bool> zoneStatusIsInZone({required ApiZoneStatus status}) =>
    RustLib.instance.api.crateApiZoneStatusIsInZone(status: status);

/// Check if the zone status is TooLow.
Future<bool> zoneStatusIsTooLow({required ApiZoneStatus status}) =>
    RustLib.instance.api.crateApiZoneStatusIsTooLow(status: status);

/// Check if the zone status is TooHigh.
Future<bool> zoneStatusIsTooHigh({required ApiZoneStatus status}) =>
    RustLib.instance.api.crateApiZoneStatusIsTooHigh(status: status);

/// Convert ZoneStatus to a string representation.
Future<String> zoneStatusToString({required ApiZoneStatus status}) =>
    RustLib.instance.api.crateApiZoneStatusToString(status: status);

/// Create a custom training plan and save it to disk.
///
/// # Arguments
///
/// * `name` - Plan name (used as filename)
/// * `phase_names` - Name for each phase
/// * `phase_zones` - Target zone (1-5) for each phase
/// * `phase_durations` - Duration in seconds for each phase
/// * `max_hr` - User's maximum heart rate
Future<void> createCustomPlan({
  required String name,
  required List<String> phaseNames,
  required List<int> phaseZones,
  required List<int> phaseDurations,
  required int maxHr,
}) => RustLib.instance.api.crateApiCreateCustomPlan(
  name: name,
  phaseNames: phaseNames,
  phaseZones: phaseZones,
  phaseDurations: phaseDurations,
  maxHr: maxHr,
);

/// Delete a training plan by name.
Future<void> deletePlan({required String name}) =>
    RustLib.instance.api.crateApiDeletePlan(name: name);

/// Get details of a training plan by name.
///
/// Returns parallel arrays for FRB compatibility.
Future<ApiPlanDetails> getPlanDetails({required String name}) =>
    RustLib.instance.api.crateApiGetPlanDetails(name: name);

/// Get comprehensive analytics data from all completed sessions.
Future<ApiAnalyticsData> getAnalytics() =>
    RustLib.instance.api.crateApiGetAnalytics();

/// Get the summary from analytics data.
Future<ApiAnalyticsSummary> analyticsSummary({
  required ApiAnalyticsData data,
}) => RustLib.instance.api.crateApiAnalyticsSummary(data: data);

/// Get the number of weekly summaries.
Future<int> analyticsWeeksCount({required ApiAnalyticsData data}) =>
    RustLib.instance.api.crateApiAnalyticsWeeksCount(data: data);

/// Get a weekly summary at the given index.
Future<ApiWeeklySummary?> analyticsWeeklyAt({
  required ApiAnalyticsData data,
  required int index,
}) => RustLib.instance.api.crateApiAnalyticsWeeklyAt(data: data, index: index);

/// Get the number of HR trend points.
Future<int> analyticsHrTrendCount({required ApiAnalyticsData data}) =>
    RustLib.instance.api.crateApiAnalyticsHrTrendCount(data: data);

/// Get an HR trend point at the given index.
Future<ApiTrendPoint?> analyticsHrTrendAt({
  required ApiAnalyticsData data,
  required int index,
}) => RustLib.instance.api.crateApiAnalyticsHrTrendAt(data: data, index: index);

/// Get the number of volume trend points.
Future<int> analyticsVolumeTrendCount({required ApiAnalyticsData data}) =>
    RustLib.instance.api.crateApiAnalyticsVolumeTrendCount(data: data);

/// Get a volume trend point at the given index.
Future<ApiTrendPoint?> analyticsVolumeTrendAt({
  required ApiAnalyticsData data,
  required int index,
}) => RustLib.instance.api.crateApiAnalyticsVolumeTrendAt(
  data: data,
  index: index,
);

/// Get the number of consistency trend points.
Future<int> analyticsConsistencyCount({required ApiAnalyticsData data}) =>
    RustLib.instance.api.crateApiAnalyticsConsistencyCount(data: data);

/// Get a consistency trend point at the given index.
Future<ApiTrendPoint?> analyticsConsistencyAt({
  required ApiAnalyticsData data,
  required int index,
}) => RustLib.instance.api.crateApiAnalyticsConsistencyAt(
  data: data,
  index: index,
);

/// Get training load metrics (CTL/ATL/TSB) from all completed sessions.
Future<ApiTrainingLoadData> getTrainingLoad() =>
    RustLib.instance.api.crateApiGetTrainingLoad();

/// Get readiness score based on available HRV and resting HR data.
Future<ApiReadinessData> getReadinessScore() =>
    RustLib.instance.api.crateApiGetReadinessScore();

/// Get all available workout templates.
Future<List<ApiWorkoutTemplate>> getWorkoutTemplates() =>
    RustLib.instance.api.crateApiGetWorkoutTemplates();

/// Start a workout from a template ID by converting it to a plan.
Future<void> startTemplateWorkout({
  required String templateId,
  required int maxHr,
}) => RustLib.instance.api.crateApiStartTemplateWorkout(
  templateId: templateId,
  maxHr: maxHr,
);

/// Export a session as TCX format.
Future<String> exportSessionTcx({required String sessionId}) =>
    RustLib.instance.api.crateApiExportSessionTcx(sessionId: sessionId);

/// Export a session as GPX format.
Future<String> exportSessionGpx({required String sessionId}) =>
    RustLib.instance.api.crateApiExportSessionGpx(sessionId: sessionId);

/// Get an adapted version of a plan based on current readiness.
Future<ApiAdaptedPlan> getAdaptedPlan({required String planName}) =>
    RustLib.instance.api.crateApiGetAdaptedPlan(planName: planName);

/// Get the current periodization plan (if any).
///
/// Returns a 5K plan starting today as a default for now.
Future<ApiPeriodizationData> getPeriodizationPlan() =>
    RustLib.instance.api.crateApiGetPeriodizationPlan();

/// Get resting HR statistics and trend.
Future<ApiRestingHrStats> getRestingHrStats() =>
    RustLib.instance.api.crateApiGetRestingHrStats();

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiCompletedSession>>
abstract class ApiCompletedSession implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiConnectionStatus>>
abstract class ApiConnectionStatus implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiFilteredHeartRate>>
abstract class ApiFilteredHeartRate implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiPhaseProgress>>
abstract class ApiPhaseProgress implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiSample>>
abstract class ApiSample implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiSessionProgress>>
abstract class ApiSessionProgress implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiSessionState>>
abstract class ApiSessionState implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiSessionSummaryPreview>>
abstract class ApiSessionSummaryPreview implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ApiZoneStatus>>
abstract class ApiZoneStatus implements RustOpaqueInterface {}

// Rust type: RustOpaqueNom<flutter_rust_bridge::for_generated::RustAutoOpaqueInner< Receiver < ApiBatteryLevel >>>
abstract class ReceiverApiBatteryLevel implements RustOpaqueInterface {}

/// Adapted plan for the FFI boundary.
class ApiAdaptedPlan {
  /// Original plan name.
  final String originalName;

  /// Adjustment reason.
  final String reason;

  /// Adjustment message.
  final String message;

  /// Zone delta applied.
  final int zoneDelta;

  /// Duration factor applied.
  final double durationFactor;

  /// Adjusted phase names.
  final List<String> phaseNames;

  /// Adjusted phase zones (1-5).
  final Uint8List phaseZones;

  /// Adjusted phase durations in seconds.
  final Uint32List phaseDurations;

  const ApiAdaptedPlan({
    required this.originalName,
    required this.reason,
    required this.message,
    required this.zoneDelta,
    required this.durationFactor,
    required this.phaseNames,
    required this.phaseZones,
    required this.phaseDurations,
  });

  @override
  int get hashCode =>
      originalName.hashCode ^
      reason.hashCode ^
      message.hashCode ^
      zoneDelta.hashCode ^
      durationFactor.hashCode ^
      phaseNames.hashCode ^
      phaseZones.hashCode ^
      phaseDurations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiAdaptedPlan &&
          runtimeType == other.runtimeType &&
          originalName == other.originalName &&
          reason == other.reason &&
          message == other.message &&
          zoneDelta == other.zoneDelta &&
          durationFactor == other.durationFactor &&
          phaseNames == other.phaseNames &&
          phaseZones == other.phaseZones &&
          phaseDurations == other.phaseDurations;
}

/// Opaque analytics data holder.
class ApiAnalyticsData {
  /// Overall summary statistics.
  final ApiAnalyticsSummary summary;

  /// Weekly breakdown of training data.
  final List<ApiWeeklySummary> weeklySummaries;

  /// Average HR per session over time.
  final List<ApiTrendPoint> hrTrend;

  /// Training volume (minutes per week) over time.
  final List<ApiTrendPoint> volumeTrend;

  /// Sessions per week over time.
  final List<ApiTrendPoint> consistencyTrend;

  const ApiAnalyticsData({
    required this.summary,
    required this.weeklySummaries,
    required this.hrTrend,
    required this.volumeTrend,
    required this.consistencyTrend,
  });

  @override
  int get hashCode =>
      summary.hashCode ^
      weeklySummaries.hashCode ^
      hrTrend.hashCode ^
      volumeTrend.hashCode ^
      consistencyTrend.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiAnalyticsData &&
          runtimeType == other.runtimeType &&
          summary == other.summary &&
          weeklySummaries == other.weeklySummaries &&
          hrTrend == other.hrTrend &&
          volumeTrend == other.volumeTrend &&
          consistencyTrend == other.consistencyTrend;
}

/// Analytics summary for the FFI boundary.
class ApiAnalyticsSummary {
  /// Total number of completed sessions.
  final int totalSessions;

  /// Total training duration in seconds.
  final int totalDurationSecs;

  /// Overall average heart rate.
  final int overallAvgHr;

  /// Overall time in each zone (5 elements).
  final Uint32List overallTimeInZone;

  /// Number of weekly summaries.
  final int weeksCount;

  /// Number of HR trend points.
  final int hrTrendCount;

  /// Number of volume trend points.
  final int volumeTrendCount;

  const ApiAnalyticsSummary({
    required this.totalSessions,
    required this.totalDurationSecs,
    required this.overallAvgHr,
    required this.overallTimeInZone,
    required this.weeksCount,
    required this.hrTrendCount,
    required this.volumeTrendCount,
  });

  @override
  int get hashCode =>
      totalSessions.hashCode ^
      totalDurationSecs.hashCode ^
      overallAvgHr.hashCode ^
      overallTimeInZone.hashCode ^
      weeksCount.hashCode ^
      hrTrendCount.hashCode ^
      volumeTrendCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiAnalyticsSummary &&
          runtimeType == other.runtimeType &&
          totalSessions == other.totalSessions &&
          totalDurationSecs == other.totalDurationSecs &&
          overallAvgHr == other.overallAvgHr &&
          overallTimeInZone == other.overallTimeInZone &&
          weeksCount == other.weeksCount &&
          hrTrendCount == other.hrTrendCount &&
          volumeTrendCount == other.volumeTrendCount;
}

/// Battery level data for FFI boundary (FRB-compatible).
///
/// This is a simplified version of domain::BatteryLevel that uses u64 timestamps
/// instead of SystemTime to be compatible with Flutter Rust Bridge.
class ApiBatteryLevel {
  /// Battery level as a percentage (0-100).
  final int? level;

  /// Whether the device is currently charging.
  final bool isCharging;

  /// Unix timestamp in milliseconds when this battery level was measured.
  final BigInt timestamp;

  const ApiBatteryLevel({
    this.level,
    required this.isCharging,
    required this.timestamp,
  });

  @override
  int get hashCode => level.hashCode ^ isCharging.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiBatteryLevel &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          isCharging == other.isCharging &&
          timestamp == other.timestamp;
}

class ApiCue {
  /// Unique identifier for this cue instance.
  final String id;

  /// Which rule triggered this cue (0=TargetZone, 1=Inactivity, 2=Overwork).
  final int source;

  /// Short machine-readable label, e.g. `"raise_hr"`.
  final String label;

  /// Human-readable message for the user.
  final String message;

  /// Priority (0=Low, 1=Normal, 2=High, 3=Critical).
  final int priority;

  /// Unix timestamp in milliseconds when this cue was generated.
  final BigInt generatedAtMillis;

  const ApiCue({
    required this.id,
    required this.source,
    required this.label,
    required this.message,
    required this.priority,
    required this.generatedAtMillis,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      label.hashCode ^
      message.hashCode ^
      priority.hashCode ^
      generatedAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiCue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          label == other.label &&
          message == other.message &&
          priority == other.priority &&
          generatedAtMillis == other.generatedAtMillis;
}

/// A single day's training load metrics for FFI.
class ApiLoadPoint {
  /// Unix timestamp in millis.
  final PlatformInt64 timestampMillis;

  /// Chronic Training Load.
  final double ctl;

  /// Acute Training Load.
  final double atl;

  /// Training Stress Balance.
  final double tsb;

  const ApiLoadPoint({
    required this.timestampMillis,
    required this.ctl,
    required this.atl,
    required this.tsb,
  });

  @override
  int get hashCode =>
      timestampMillis.hashCode ^ ctl.hashCode ^ atl.hashCode ^ tsb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiLoadPoint &&
          runtimeType == other.runtimeType &&
          timestampMillis == other.timestampMillis &&
          ctl == other.ctl &&
          atl == other.atl &&
          tsb == other.tsb;
}

/// Periodization plan data for the FFI boundary.
class ApiPeriodizationData {
  /// Plan name.
  final String name;

  /// Goal description.
  final String goal;

  /// Start date as ISO string.
  final String startDate;

  /// End date as ISO string.
  final String endDate;

  /// Total weeks.
  final int totalWeeks;

  /// Current block index (0-based), or -1 if not in any block.
  final int currentBlockIndex;

  /// Block names.
  final List<String> blockNames;

  /// Block types as strings.
  final List<String> blockTypes;

  /// Block durations in weeks.
  final Uint8List blockWeeks;

  const ApiPeriodizationData({
    required this.name,
    required this.goal,
    required this.startDate,
    required this.endDate,
    required this.totalWeeks,
    required this.currentBlockIndex,
    required this.blockNames,
    required this.blockTypes,
    required this.blockWeeks,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      goal.hashCode ^
      startDate.hashCode ^
      endDate.hashCode ^
      totalWeeks.hashCode ^
      currentBlockIndex.hashCode ^
      blockNames.hashCode ^
      blockTypes.hashCode ^
      blockWeeks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPeriodizationData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          goal == other.goal &&
          startDate == other.startDate &&
          endDate == other.endDate &&
          totalWeeks == other.totalWeeks &&
          currentBlockIndex == other.currentBlockIndex &&
          blockNames == other.blockNames &&
          blockTypes == other.blockTypes &&
          blockWeeks == other.blockWeeks;
}

/// Plan details for the FFI boundary.
class ApiPlanDetails {
  /// Plan name.
  final String name;

  /// Phase names.
  final List<String> phaseNames;

  /// Target zone number (1-5) per phase.
  final Uint8List phaseZones;

  /// Duration in seconds per phase.
  final Uint32List phaseDurations;

  /// Max heart rate.
  final int maxHr;

  /// Creation timestamp in milliseconds.
  final PlatformInt64 createdAtMillis;

  const ApiPlanDetails({
    required this.name,
    required this.phaseNames,
    required this.phaseZones,
    required this.phaseDurations,
    required this.maxHr,
    required this.createdAtMillis,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      phaseNames.hashCode ^
      phaseZones.hashCode ^
      phaseDurations.hashCode ^
      maxHr.hashCode ^
      createdAtMillis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiPlanDetails &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          phaseNames == other.phaseNames &&
          phaseZones == other.phaseZones &&
          phaseDurations == other.phaseDurations &&
          maxHr == other.maxHr &&
          createdAtMillis == other.createdAtMillis;
}

/// Readiness data for the FFI boundary.
class ApiReadinessData {
  /// Overall readiness score (0-100).
  final int score;

  /// Readiness level: "Ready", "Moderate", or "Rest".
  final String level;

  /// HRV component score (0-100).
  final double hrvComponent;

  /// Resting HR component score (0-100).
  final double rhrComponent;

  /// Training load component score (0-100).
  final double loadComponent;

  /// Human-readable recommendation.
  final String recommendation;

  const ApiReadinessData({
    required this.score,
    required this.level,
    required this.hrvComponent,
    required this.rhrComponent,
    required this.loadComponent,
    required this.recommendation,
  });

  @override
  int get hashCode =>
      score.hashCode ^
      level.hashCode ^
      hrvComponent.hashCode ^
      rhrComponent.hashCode ^
      loadComponent.hashCode ^
      recommendation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiReadinessData &&
          runtimeType == other.runtimeType &&
          score == other.score &&
          level == other.level &&
          hrvComponent == other.hrvComponent &&
          rhrComponent == other.rhrComponent &&
          loadComponent == other.loadComponent &&
          recommendation == other.recommendation;
}

/// Resting HR stats for the FFI boundary.
class ApiRestingHrStats {
  /// Current resting HR, if available.
  final int? currentBpm;

  /// 7-day average, if available.
  final double? sevenDayAvg;

  /// 30-day average, if available.
  final double? thirtyDayAvg;

  /// Trend direction: "Improving", "Stable", "Worsening", "Insufficient".
  final String trendDirection;

  /// Trend points for charting.
  final List<ApiTrendPoint> trendPoints;

  const ApiRestingHrStats({
    this.currentBpm,
    this.sevenDayAvg,
    this.thirtyDayAvg,
    required this.trendDirection,
    required this.trendPoints,
  });

  @override
  int get hashCode =>
      currentBpm.hashCode ^
      sevenDayAvg.hashCode ^
      thirtyDayAvg.hashCode ^
      trendDirection.hashCode ^
      trendPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiRestingHrStats &&
          runtimeType == other.runtimeType &&
          currentBpm == other.currentBpm &&
          sevenDayAvg == other.sevenDayAvg &&
          thirtyDayAvg == other.thirtyDayAvg &&
          trendDirection == other.trendDirection &&
          trendPoints == other.trendPoints;
}

/// Training load metrics for the FFI boundary.
class ApiTrainingLoadData {
  /// Current CTL (fitness).
  final double currentCtl;

  /// Current ATL (fatigue).
  final double currentAtl;

  /// Current TSB (form).
  final double currentTsb;

  /// Daily CTL/ATL/TSB history.
  final List<ApiLoadPoint> loadHistory;

  /// TRIMP per session.
  final List<ApiTrendPoint> sessionTrimp;

  const ApiTrainingLoadData({
    required this.currentCtl,
    required this.currentAtl,
    required this.currentTsb,
    required this.loadHistory,
    required this.sessionTrimp,
  });

  @override
  int get hashCode =>
      currentCtl.hashCode ^
      currentAtl.hashCode ^
      currentTsb.hashCode ^
      loadHistory.hashCode ^
      sessionTrimp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTrainingLoadData &&
          runtimeType == other.runtimeType &&
          currentCtl == other.currentCtl &&
          currentAtl == other.currentAtl &&
          currentTsb == other.currentTsb &&
          loadHistory == other.loadHistory &&
          sessionTrimp == other.sessionTrimp;
}

/// Trend point for the FFI boundary.
class ApiTrendPoint {
  /// Unix timestamp in milliseconds.
  final PlatformInt64 timestampMillis;

  /// Metric value.
  final double value;

  const ApiTrendPoint({required this.timestampMillis, required this.value});

  @override
  int get hashCode => timestampMillis.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiTrendPoint &&
          runtimeType == other.runtimeType &&
          timestampMillis == other.timestampMillis &&
          value == other.value;
}

/// Weekly summary for the FFI boundary.
class ApiWeeklySummary {
  /// Monday of the week as Unix millis.
  final PlatformInt64 weekStartMillis;

  /// Number of sessions.
  final int sessionCount;

  /// Total duration in seconds.
  final int totalDurationSecs;

  /// Average HR across the week.
  final int avgHr;

  /// Time in each zone.
  final Uint32List timeInZone;

  const ApiWeeklySummary({
    required this.weekStartMillis,
    required this.sessionCount,
    required this.totalDurationSecs,
    required this.avgHr,
    required this.timeInZone,
  });

  @override
  int get hashCode =>
      weekStartMillis.hashCode ^
      sessionCount.hashCode ^
      totalDurationSecs.hashCode ^
      avgHr.hashCode ^
      timeInZone.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiWeeklySummary &&
          runtimeType == other.runtimeType &&
          weekStartMillis == other.weekStartMillis &&
          sessionCount == other.sessionCount &&
          totalDurationSecs == other.totalDurationSecs &&
          avgHr == other.avgHr &&
          timeInZone == other.timeInZone;
}

/// Workout template for the FFI boundary.
class ApiWorkoutTemplate {
  /// Unique template ID.
  final String id;

  /// Template name.
  final String name;

  /// Description of the workout.
  final String description;

  /// Sport category.
  final String sport;

  /// Difficulty level.
  final String difficulty;

  /// Estimated duration in minutes.
  final int durationMins;

  /// Number of phases.
  final int phaseCount;

  const ApiWorkoutTemplate({
    required this.id,
    required this.name,
    required this.description,
    required this.sport,
    required this.difficulty,
    required this.durationMins,
    required this.phaseCount,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      description.hashCode ^
      sport.hashCode ^
      difficulty.hashCode ^
      durationMins.hashCode ^
      phaseCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ApiWorkoutTemplate &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          description == other.description &&
          sport == other.sport &&
          difficulty == other.difficulty &&
          durationMins == other.durationMins &&
          phaseCount == other.phaseCount;
}

/// Format for exporting session data.
///
/// Specifies the output format when exporting a completed training session.
enum ExportFormat {
  /// Export as comma-separated values (CSV) with timestamp, bpm, and zone columns
  csv,

  /// Export as pretty-printed JSON containing the full session structure
  json,

  /// Export as human-readable text summary with statistics
  summary,
}

/// Log message that can be sent to Flutter for debugging.
///
/// This struct represents a single log entry with level, target module,
/// timestamp, and message content. It's designed to be sent across the FFI
/// boundary to Flutter for display in the debug console.
class LogMessage {
  /// Log level (TRACE, DEBUG, INFO, WARN, ERROR)
  final String level;

  /// Module path where the log originated (e.g., "heart_beat::adapters")
  final String target;

  /// Timestamp in milliseconds since Unix epoch
  final BigInt timestamp;

  /// The actual log message
  final String message;

  const LogMessage({
    required this.level,
    required this.target,
    required this.timestamp,
    required this.message,
  });

  @override
  int get hashCode =>
      level.hashCode ^ target.hashCode ^ timestamp.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogMessage &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          target == other.target &&
          timestamp == other.timestamp &&
          message == other.message;
}
