// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain/heart_rate.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiFilteredHeartRatePtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRatePtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogMessage> dco_decode_StreamSink_log_message_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  DiscoveredDevice dco_decode_discovered_device(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<DiscoveredDevice> dco_decode_list_discovered_device(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LogMessage dco_decode_log_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Zone dco_decode_zone(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogMessage> sse_decode_StreamSink_log_message_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  DiscoveredDevice sse_decode_discovered_device(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<DiscoveredDevice> sse_decode_list_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LogMessage sse_decode_log_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_AnyhowException(
    AnyhowException raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict>
  cst_encode_StreamSink_log_message_Dco(RustStreamSink<LogMessage> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_log_message,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Double> cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_f_64(cst_encode_f_64(raw));
  }

  @protected
  ffi.Pointer<ffi.Uint8> cst_encode_box_autoadd_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_u_8(cst_encode_u_8(raw));
  }

  @protected
  ffi.Pointer<wire_cst_list_discovered_device>
  cst_encode_list_discovered_device(List<DiscoveredDevice> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_discovered_device(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_discovered_device(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(
    Uint8List raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(
    String? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Double> cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  ffi.Pointer<ffi.Uint8> cst_encode_opt_box_autoadd_u_8(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_u_8(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  int cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_discovered_device(
    DiscoveredDevice apiObj,
    wire_cst_discovered_device wireObj,
  ) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_opt_String(apiObj.name);
    wireObj.rssi = cst_encode_i_16(apiObj.rssi);
  }

  @protected
  void cst_api_fill_to_wire_log_message(
    LogMessage apiObj,
    wire_cst_log_message wireObj,
  ) {
    wireObj.level = cst_encode_String(apiObj.level);
    wireObj.target = cst_encode_String(apiObj.target);
    wireObj.timestamp = cst_encode_u_64(apiObj.timestamp);
    wireObj.message = cst_encode_String(apiObj.message);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_16(int raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_zone(Zone raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_message_Dco(
    RustStreamSink<LogMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_device(
    DiscoveredDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_discovered_device(
    List<DiscoveredDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_message(LogMessage self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
        'store_dart_post_cobject',
      );
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__connect_device(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> device_id,
  ) {
    return _wire__crate__api__connect_device(port_, device_id);
  }

  late final _wire__crate__api__connect_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_heart_beat_wire__crate__api__connect_device');
  late final _wire__crate__api__connect_device =
      _wire__crate__api__connect_devicePtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__create_hr_stream(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__create_hr_stream(port_, sink);
  }

  late final _wire__crate__api__create_hr_streamPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_heart_beat_wire__crate__api__create_hr_stream');
  late final _wire__crate__api__create_hr_stream =
      _wire__crate__api__create_hr_streamPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__disconnect(int port_) {
    return _wire__crate__api__disconnect(port_);
  }

  late final _wire__crate__api__disconnectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_heart_beat_wire__crate__api__disconnect',
      );
  late final _wire__crate__api__disconnect = _wire__crate__api__disconnectPtr
      .asFunction<void Function(int)>();

  void wire__crate__api__emit_hr_data(int port_, int data) {
    return _wire__crate__api__emit_hr_data(port_, data);
  }

  late final _wire__crate__api__emit_hr_dataPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__emit_hr_data',
      );
  late final _wire__crate__api__emit_hr_data =
      _wire__crate__api__emit_hr_dataPtr.asFunction<void Function(int, int)>();

  void wire__crate__api__hr_battery_level(int port_, int data) {
    return _wire__crate__api__hr_battery_level(port_, data);
  }

  late final _wire__crate__api__hr_battery_levelPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__hr_battery_level',
      );
  late final _wire__crate__api__hr_battery_level =
      _wire__crate__api__hr_battery_levelPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__hr_filtered_bpm(int port_, int data) {
    return _wire__crate__api__hr_filtered_bpm(port_, data);
  }

  late final _wire__crate__api__hr_filtered_bpmPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__hr_filtered_bpm',
      );
  late final _wire__crate__api__hr_filtered_bpm =
      _wire__crate__api__hr_filtered_bpmPtr
          .asFunction<void Function(int, int)>();

  void wire__crate__api__hr_raw_bpm(int port_, int data) {
    return _wire__crate__api__hr_raw_bpm(port_, data);
  }

  late final _wire__crate__api__hr_raw_bpmPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__hr_raw_bpm',
      );
  late final _wire__crate__api__hr_raw_bpm = _wire__crate__api__hr_raw_bpmPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__hr_rmssd(int port_, int data) {
    return _wire__crate__api__hr_rmssd(port_, data);
  }

  late final _wire__crate__api__hr_rmssdPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__hr_rmssd',
      );
  late final _wire__crate__api__hr_rmssd = _wire__crate__api__hr_rmssdPtr
      .asFunction<void Function(int, int)>();

  void wire__crate__api__hr_timestamp(int port_, int data) {
    return _wire__crate__api__hr_timestamp(port_, data);
  }

  late final _wire__crate__api__hr_timestampPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.UintPtr)>>(
        'frbgen_heart_beat_wire__crate__api__hr_timestamp',
      );
  late final _wire__crate__api__hr_timestamp =
      _wire__crate__api__hr_timestampPtr.asFunction<void Function(int, int)>();

  void wire__crate__api__hr_zone(int port_, int data, int max_hr) {
    return _wire__crate__api__hr_zone(port_, data, max_hr);
  }

  late final _wire__crate__api__hr_zonePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.UintPtr, ffi.Uint16)
        >
      >('frbgen_heart_beat_wire__crate__api__hr_zone');
  late final _wire__crate__api__hr_zone = _wire__crate__api__hr_zonePtr
      .asFunction<void Function(int, int, int)>();

  void wire__crate__api__init_logging(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> sink,
  ) {
    return _wire__crate__api__init_logging(port_, sink);
  }

  late final _wire__crate__api__init_loggingPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )
        >
      >('frbgen_heart_beat_wire__crate__api__init_logging');
  late final _wire__crate__api__init_logging =
      _wire__crate__api__init_loggingPtr
          .asFunction<
            void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>)
          >();

  void wire__crate__api__init_panic_handler(int port_) {
    return _wire__crate__api__init_panic_handler(port_);
  }

  late final _wire__crate__api__init_panic_handlerPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_heart_beat_wire__crate__api__init_panic_handler',
      );
  late final _wire__crate__api__init_panic_handler =
      _wire__crate__api__init_panic_handlerPtr.asFunction<void Function(int)>();

  void wire__crate__api__init_platform(int port_) {
    return _wire__crate__api__init_platform(port_);
  }

  late final _wire__crate__api__init_platformPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_heart_beat_wire__crate__api__init_platform',
      );
  late final _wire__crate__api__init_platform =
      _wire__crate__api__init_platformPtr.asFunction<void Function(int)>();

  void wire__crate__api__scan_devices(int port_) {
    return _wire__crate__api__scan_devices(port_);
  }

  late final _wire__crate__api__scan_devicesPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_heart_beat_wire__crate__api__scan_devices',
      );
  late final _wire__crate__api__scan_devices =
      _wire__crate__api__scan_devicesPtr.asFunction<void Function(int)>();

  void wire__crate__api__start_mock_mode(int port_) {
    return _wire__crate__api__start_mock_mode(port_);
  }

  late final _wire__crate__api__start_mock_modePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
        'frbgen_heart_beat_wire__crate__api__start_mock_mode',
      );
  late final _wire__crate__api__start_mock_mode =
      _wire__crate__api__start_mock_modePtr.asFunction<void Function(int)>();

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_heart_beat_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate',
      );
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRatePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
        'frbgen_heart_beat_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate',
      );
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRatePtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<ffi.Double> cst_new_box_autoadd_f_64(double value) {
    return _cst_new_box_autoadd_f_64(value);
  }

  late final _cst_new_box_autoadd_f_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Double> Function(ffi.Double)>>(
        'frbgen_heart_beat_cst_new_box_autoadd_f_64',
      );
  late final _cst_new_box_autoadd_f_64 = _cst_new_box_autoadd_f_64Ptr
      .asFunction<ffi.Pointer<ffi.Double> Function(double)>();

  ffi.Pointer<ffi.Uint8> cst_new_box_autoadd_u_8(int value) {
    return _cst_new_box_autoadd_u_8(value);
  }

  late final _cst_new_box_autoadd_u_8Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Uint8> Function(ffi.Uint8)>>(
        'frbgen_heart_beat_cst_new_box_autoadd_u_8',
      );
  late final _cst_new_box_autoadd_u_8 = _cst_new_box_autoadd_u_8Ptr
      .asFunction<ffi.Pointer<ffi.Uint8> Function(int)>();

  ffi.Pointer<wire_cst_list_discovered_device> cst_new_list_discovered_device(
    int len,
  ) {
    return _cst_new_list_discovered_device(len);
  }

  late final _cst_new_list_discovered_devicePtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_discovered_device> Function(ffi.Int32)
        >
      >('frbgen_heart_beat_cst_new_list_discovered_device');
  late final _cst_new_list_discovered_device =
      _cst_new_list_discovered_devicePtr
          .asFunction<
            ffi.Pointer<wire_cst_list_discovered_device> Function(int)
          >();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<
        ffi.NativeFunction<
          ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)
        >
      >('frbgen_heart_beat_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
        'dummy_method_to_enforce_bundling',
      );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPostCObjectFnType =
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;
typedef DartPostCObjectFnTypeFunction =
    ffi.Bool Function(DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction =
    bool Function(DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPort = ffi.Int64;
typedef DartDartPort = int;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_discovered_device extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  @ffi.Int16()
  external int rssi;
}

final class wire_cst_list_discovered_device extends ffi.Struct {
  external ffi.Pointer<wire_cst_discovered_device> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_log_message extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> level;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> target;

  @ffi.Uint64()
  external int timestamp;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> message;
}
