// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/heart_rate.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiCompletedSessionPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiConnectionStatusPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiFilteredHeartRatePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiPhaseProgressPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiSessionProgressPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiSessionStatePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiSessionSummaryPreviewPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiZoneStatusPtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ApiCompletedSession
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    dynamic raw,
  );

  @protected
  ApiConnectionStatus
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiPhaseProgress
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    dynamic raw,
  );

  @protected
  ApiSessionProgress
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    dynamic raw,
  );

  @protected
  ApiSessionState
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    dynamic raw,
  );

  @protected
  ApiSessionSummaryPreview
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    dynamic raw,
  );

  @protected
  ApiZoneStatus
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    dynamic raw,
  );

  @protected
  ApiCompletedSession
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    dynamic raw,
  );

  @protected
  ApiConnectionStatus
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiPhaseProgress
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    dynamic raw,
  );

  @protected
  ApiSessionProgress
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    dynamic raw,
  );

  @protected
  ApiSessionState
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    dynamic raw,
  );

  @protected
  ApiSessionSummaryPreview
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    dynamic raw,
  );

  @protected
  ApiZoneStatus
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    dynamic raw,
  );

  @protected
  ApiCompletedSession
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    dynamic raw,
  );

  @protected
  ApiConnectionStatus
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiPhaseProgress
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    dynamic raw,
  );

  @protected
  ApiSessionProgress
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    dynamic raw,
  );

  @protected
  ApiSessionState
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    dynamic raw,
  );

  @protected
  ApiSessionSummaryPreview
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    dynamic raw,
  );

  @protected
  ApiZoneStatus
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiConnectionStatus>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiSessionProgress>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiBatteryLevel> dco_decode_StreamSink_api_battery_level_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogMessage> dco_decode_StreamSink_log_message_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ApiBatteryLevel dco_decode_api_battery_level(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ApiCompletedSession
  dco_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    dynamic raw,
  );

  @protected
  ApiBatteryLevel dco_decode_box_autoadd_api_battery_level(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  (PlatformInt64, int) dco_decode_box_autoadd_record_i_64_u_16(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  DiscoveredDevice dco_decode_discovered_device(dynamic raw);

  @protected
  ExportFormat dco_decode_export_format(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<ApiSessionSummaryPreview>
  dco_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    dynamic raw,
  );

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<DiscoveredDevice> dco_decode_list_discovered_device(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LogMessage dco_decode_log_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ApiCompletedSession?
  dco_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    dynamic raw,
  );

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  (PlatformInt64, int)? dco_decode_opt_box_autoadd_record_i_64_u_16(
    dynamic raw,
  );

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  (PlatformInt64, int) dco_decode_record_i_64_u_16(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Zone dco_decode_zone(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ApiCompletedSession
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiConnectionStatus
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiPhaseProgress
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionProgress
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionState
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionSummaryPreview
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    SseDeserializer deserializer,
  );

  @protected
  ApiZoneStatus
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    SseDeserializer deserializer,
  );

  @protected
  ApiCompletedSession
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiConnectionStatus
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiPhaseProgress
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionProgress
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionState
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionSummaryPreview
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    SseDeserializer deserializer,
  );

  @protected
  ApiZoneStatus
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    SseDeserializer deserializer,
  );

  @protected
  ApiCompletedSession
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiConnectionStatus
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiPhaseProgress
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionProgress
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionState
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    SseDeserializer deserializer,
  );

  @protected
  ApiSessionSummaryPreview
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    SseDeserializer deserializer,
  );

  @protected
  ApiZoneStatus
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiConnectionStatus>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiSessionProgress>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiBatteryLevel> sse_decode_StreamSink_api_battery_level_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogMessage> sse_decode_StreamSink_log_message_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ApiBatteryLevel sse_decode_api_battery_level(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ApiCompletedSession
  sse_decode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    SseDeserializer deserializer,
  );

  @protected
  ApiBatteryLevel sse_decode_box_autoadd_api_battery_level(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  (PlatformInt64, int) sse_decode_box_autoadd_record_i_64_u_16(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  DiscoveredDevice sse_decode_discovered_device(SseDeserializer deserializer);

  @protected
  ExportFormat sse_decode_export_format(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<ApiSessionSummaryPreview>
  sse_decode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    SseDeserializer deserializer,
  );

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<DiscoveredDevice> sse_decode_list_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LogMessage sse_decode_log_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ApiCompletedSession?
  sse_decode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  (PlatformInt64, int)? sse_decode_opt_box_autoadd_record_i_64_u_16(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  (PlatformInt64, int) sse_decode_record_i_64_u_16(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String
  cst_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus_Dco(
    RustStreamSink<ApiConnectionStatus> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String
  cst_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String
  cst_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress_Dco(
    RustStreamSink<ApiSessionProgress> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_StreamSink_api_battery_level_Dco(
    RustStreamSink<ApiBatteryLevel> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_api_battery_level,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_StreamSink_log_message_Dco(RustStreamSink<LogMessage> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_log_message,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  JSAny cst_encode_api_battery_level(ApiBatteryLevel raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_opt_box_autoadd_u_8(raw.level),
      cst_encode_bool(raw.isCharging),
      cst_encode_u_64(raw.timestamp),
    ].jsify()!;
  }

  @protected
  int
  cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
      raw,
    );
  }

  @protected
  JSAny cst_encode_box_autoadd_api_battery_level(ApiBatteryLevel raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_api_battery_level(raw);
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  JSAny cst_encode_box_autoadd_record_i_64_u_16((PlatformInt64, int) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_record_i_64_u_16(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_8(raw);
  }

  @protected
  JSAny cst_encode_discovered_device(DiscoveredDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_opt_String(raw.name),
      cst_encode_i_16(raw.rssi),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny
  cst_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    List<ApiSessionSummaryPreview> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw
        .map(
          cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview,
        )
        .toList()
        .jsify()!;
  }

  @protected
  JSAny cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_String).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_discovered_device(List<DiscoveredDevice> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_discovered_device).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_32_strict(Uint32List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_log_message(LogMessage raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.level),
      cst_encode_String(raw.target),
      cst_encode_u_64(raw.timestamp),
      cst_encode_String(raw.message),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  int?
  cst_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null
        ? null
        : cst_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
            raw,
          );
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  JSAny? cst_encode_opt_box_autoadd_record_i_64_u_16(
    (PlatformInt64, int)? raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_record_i_64_u_16(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_8(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_8(raw);
  }

  @protected
  JSAny cst_encode_record_i_64_u_16((PlatformInt64, int) raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [cst_encode_i_64(raw.$1), cst_encode_u_16(raw.$2)].jsify()!;
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview raw,
  );

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus raw,
  );

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_export_format(ExportFormat raw);

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_16(int raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_zone(Zone raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    ApiConnectionStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    ApiPhaseProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    ApiSessionProgress self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    ApiSessionState self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    ApiSessionSummaryPreview self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    ApiZoneStatus self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus_Dco(
    RustStreamSink<ApiConnectionStatus> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress_Dco(
    RustStreamSink<ApiSessionProgress> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_api_battery_level_Dco(
    RustStreamSink<ApiBatteryLevel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_message_Dco(
    RustStreamSink<LogMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_api_battery_level(
    ApiBatteryLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void
  sse_encode_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_api_battery_level(
    ApiBatteryLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_record_i_64_u_16(
    (PlatformInt64, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_device(
    DiscoveredDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_export_format(ExportFormat self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void
  sse_encode_list_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    List<ApiSessionSummaryPreview> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_discovered_device(
    List<DiscoveredDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_message(LogMessage self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void
  sse_encode_opt_box_autoadd_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    ApiCompletedSession? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_record_i_64_u_16(
    (PlatformInt64, int)? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_record_i_64_u_16(
    (PlatformInt64, int) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__connect_device(
    NativePortType port_,
    String device_id,
  ) => wasmModule.wire__crate__api__connect_device(port_, device_id);

  void wire__crate__api__connection_status_attempt(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_attempt(port_, status);

  void wire__crate__api__connection_status_device_id(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_device_id(port_, status);

  void wire__crate__api__connection_status_failure_reason(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_failure_reason(
    port_,
    status,
  );

  void wire__crate__api__connection_status_is_connected(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_is_connected(
    port_,
    status,
  );

  void wire__crate__api__connection_status_is_connecting(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_is_connecting(
    port_,
    status,
  );

  void wire__crate__api__connection_status_is_disconnected(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_is_disconnected(
    port_,
    status,
  );

  void wire__crate__api__connection_status_is_reconnect_failed(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_is_reconnect_failed(
    port_,
    status,
  );

  void wire__crate__api__connection_status_is_reconnecting(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_is_reconnecting(
    port_,
    status,
  );

  void wire__crate__api__connection_status_max_attempts(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_max_attempts(
    port_,
    status,
  );

  void wire__crate__api__connection_status_to_string(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__connection_status_to_string(port_, status);

  void wire__crate__api__create_battery_stream(
    NativePortType port_,
    String sink,
  ) => wasmModule.wire__crate__api__create_battery_stream(port_, sink);

  void wire__crate__api__create_connection_status_stream(
    NativePortType port_,
    String sink,
  ) =>
      wasmModule.wire__crate__api__create_connection_status_stream(port_, sink);

  void wire__crate__api__create_hr_stream(NativePortType port_, String sink) =>
      wasmModule.wire__crate__api__create_hr_stream(port_, sink);

  void wire__crate__api__create_session_progress_stream(
    NativePortType port_,
    String sink,
  ) => wasmModule.wire__crate__api__create_session_progress_stream(port_, sink);

  void wire__crate__api__delete_session(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__delete_session(port_, id);

  void wire__crate__api__disconnect(NativePortType port_) =>
      wasmModule.wire__crate__api__disconnect(port_);

  void wire__crate__api__dummy_battery_level_for_codegen(
    NativePortType port_,
  ) => wasmModule.wire__crate__api__dummy_battery_level_for_codegen(port_);

  void wire__crate__api__dummy_connection_status_for_codegen(
    NativePortType port_,
  ) => wasmModule.wire__crate__api__dummy_connection_status_for_codegen(port_);

  void wire__crate__api__emit_battery_data(NativePortType port_, JSAny data) =>
      wasmModule.wire__crate__api__emit_battery_data(port_, data);

  void wire__crate__api__emit_connection_status(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__emit_connection_status(port_, status);

  void wire__crate__api__emit_hr_data(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__emit_hr_data(port_, data);

  void wire__crate__api__emit_session_progress(
    NativePortType port_,
    int data,
  ) => wasmModule.wire__crate__api__emit_session_progress(port_, data);

  void wire__crate__api__export_session(
    NativePortType port_,
    String id,
    int format,
  ) => wasmModule.wire__crate__api__export_session(port_, id, format);

  void wire__crate__api__get_session(NativePortType port_, String id) =>
      wasmModule.wire__crate__api__get_session(port_, id);

  void wire__crate__api__hr_battery_level(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_battery_level(port_, data);

  void wire__crate__api__hr_filtered_bpm(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_filtered_bpm(port_, data);

  void wire__crate__api__hr_raw_bpm(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_raw_bpm(port_, data);

  void wire__crate__api__hr_rmssd(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_rmssd(port_, data);

  void wire__crate__api__hr_timestamp(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_timestamp(port_, data);

  void wire__crate__api__hr_zone(NativePortType port_, int data, int max_hr) =>
      wasmModule.wire__crate__api__hr_zone(port_, data, max_hr);

  void wire__crate__api__init_logging(NativePortType port_, String sink) =>
      wasmModule.wire__crate__api__init_logging(port_, sink);

  void wire__crate__api__init_panic_handler(NativePortType port_) =>
      wasmModule.wire__crate__api__init_panic_handler(port_);

  void wire__crate__api__init_platform(NativePortType port_) =>
      wasmModule.wire__crate__api__init_platform(port_);

  void wire__crate__api__list_plans(NativePortType port_) =>
      wasmModule.wire__crate__api__list_plans(port_);

  void wire__crate__api__list_sessions(NativePortType port_) =>
      wasmModule.wire__crate__api__list_sessions(port_);

  void wire__crate__api__pause_workout(NativePortType port_) =>
      wasmModule.wire__crate__api__pause_workout(port_);

  void wire__crate__api__phase_progress_elapsed_secs(
    NativePortType port_,
    int progress,
  ) =>
      wasmModule.wire__crate__api__phase_progress_elapsed_secs(port_, progress);

  void wire__crate__api__phase_progress_phase_index(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__phase_progress_phase_index(port_, progress);

  void wire__crate__api__phase_progress_phase_name(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__phase_progress_phase_name(port_, progress);

  void wire__crate__api__phase_progress_remaining_secs(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__phase_progress_remaining_secs(
    port_,
    progress,
  );

  void wire__crate__api__phase_progress_target_zone(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__phase_progress_target_zone(port_, progress);

  void wire__crate__api__resume_workout(NativePortType port_) =>
      wasmModule.wire__crate__api__resume_workout(port_);

  void wire__crate__api__scan_devices(NativePortType port_) =>
      wasmModule.wire__crate__api__scan_devices(port_);

  void wire__crate__api__session_end_time(NativePortType port_, int session) =>
      wasmModule.wire__crate__api__session_end_time(port_, session);

  void wire__crate__api__session_hr_sample_at(
    NativePortType port_,
    int session,
    JSAny index,
  ) => wasmModule.wire__crate__api__session_hr_sample_at(port_, session, index);

  void wire__crate__api__session_hr_samples_count(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_hr_samples_count(port_, session);

  void wire__crate__api__session_id(NativePortType port_, int session) =>
      wasmModule.wire__crate__api__session_id(port_, session);

  void wire__crate__api__session_phases_completed(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_phases_completed(port_, session);

  void wire__crate__api__session_plan_name(NativePortType port_, int session) =>
      wasmModule.wire__crate__api__session_plan_name(port_, session);

  void wire__crate__api__session_preview_avg_hr(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_avg_hr(port_, preview);

  void wire__crate__api__session_preview_duration_secs(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_duration_secs(
    port_,
    preview,
  );

  void wire__crate__api__session_preview_id(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_id(port_, preview);

  void wire__crate__api__session_preview_plan_name(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_plan_name(port_, preview);

  void wire__crate__api__session_preview_start_time(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_start_time(port_, preview);

  void wire__crate__api__session_preview_status(
    NativePortType port_,
    int preview,
  ) => wasmModule.wire__crate__api__session_preview_status(port_, preview);

  void wire__crate__api__session_progress_current_bpm(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_current_bpm(
    port_,
    progress,
  );

  void wire__crate__api__session_progress_current_phase(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_current_phase(
    port_,
    progress,
  );

  void wire__crate__api__session_progress_phase_progress(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_phase_progress(
    port_,
    progress,
  );

  void wire__crate__api__session_progress_state(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_state(port_, progress);

  void wire__crate__api__session_progress_total_elapsed_secs(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_total_elapsed_secs(
    port_,
    progress,
  );

  void wire__crate__api__session_progress_total_remaining_secs(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_total_remaining_secs(
    port_,
    progress,
  );

  void wire__crate__api__session_progress_zone_status(
    NativePortType port_,
    int progress,
  ) => wasmModule.wire__crate__api__session_progress_zone_status(
    port_,
    progress,
  );

  void wire__crate__api__session_start_time(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_start_time(port_, session);

  void wire__crate__api__session_state_is_completed(
    NativePortType port_,
    int state,
  ) => wasmModule.wire__crate__api__session_state_is_completed(port_, state);

  void wire__crate__api__session_state_is_paused(
    NativePortType port_,
    int state,
  ) => wasmModule.wire__crate__api__session_state_is_paused(port_, state);

  void wire__crate__api__session_state_is_running(
    NativePortType port_,
    int state,
  ) => wasmModule.wire__crate__api__session_state_is_running(port_, state);

  void wire__crate__api__session_state_is_stopped(
    NativePortType port_,
    int state,
  ) => wasmModule.wire__crate__api__session_state_is_stopped(port_, state);

  void wire__crate__api__session_state_to_string(
    NativePortType port_,
    int state,
  ) => wasmModule.wire__crate__api__session_state_to_string(port_, state);

  void wire__crate__api__session_status(NativePortType port_, int session) =>
      wasmModule.wire__crate__api__session_status(port_, session);

  void wire__crate__api__session_summary_avg_hr(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_summary_avg_hr(port_, session);

  void wire__crate__api__session_summary_duration_secs(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_summary_duration_secs(
    port_,
    session,
  );

  void wire__crate__api__session_summary_max_hr(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_summary_max_hr(port_, session);

  void wire__crate__api__session_summary_min_hr(
    NativePortType port_,
    int session,
  ) => wasmModule.wire__crate__api__session_summary_min_hr(port_, session);

  void wire__crate__api__session_summary_time_in_zone(
    NativePortType port_,
    int session,
  ) =>
      wasmModule.wire__crate__api__session_summary_time_in_zone(port_, session);

  void wire__crate__api__start_mock_mode(NativePortType port_) =>
      wasmModule.wire__crate__api__start_mock_mode(port_);

  void wire__crate__api__start_workout(
    NativePortType port_,
    String plan_name,
  ) => wasmModule.wire__crate__api__start_workout(port_, plan_name);

  void wire__crate__api__stop_workout(NativePortType port_) =>
      wasmModule.wire__crate__api__stop_workout(port_);

  void wire__crate__api__zone_status_is_in_zone(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__zone_status_is_in_zone(port_, status);

  void wire__crate__api__zone_status_is_too_high(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__zone_status_is_too_high(port_, status);

  void wire__crate__api__zone_status_is_too_low(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__zone_status_is_too_low(port_, status);

  void wire__crate__api__zone_status_to_string(
    NativePortType port_,
    int status,
  ) => wasmModule.wire__crate__api__zone_status_to_string(port_, status);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
        ptr,
      );

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__connect_device(
    NativePortType port_,
    String device_id,
  );

  external void wire__crate__api__connection_status_attempt(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_device_id(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_failure_reason(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_is_connected(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_is_connecting(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_is_disconnected(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_is_reconnect_failed(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_is_reconnecting(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_max_attempts(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__connection_status_to_string(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__create_battery_stream(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__create_connection_status_stream(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__create_hr_stream(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__create_session_progress_stream(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__delete_session(
    NativePortType port_,
    String id,
  );

  external void wire__crate__api__disconnect(NativePortType port_);

  external void wire__crate__api__dummy_battery_level_for_codegen(
    NativePortType port_,
  );

  external void wire__crate__api__dummy_connection_status_for_codegen(
    NativePortType port_,
  );

  external void wire__crate__api__emit_battery_data(
    NativePortType port_,
    JSAny data,
  );

  external void wire__crate__api__emit_connection_status(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__emit_hr_data(NativePortType port_, int data);

  external void wire__crate__api__emit_session_progress(
    NativePortType port_,
    int data,
  );

  external void wire__crate__api__export_session(
    NativePortType port_,
    String id,
    int format,
  );

  external void wire__crate__api__get_session(NativePortType port_, String id);

  external void wire__crate__api__hr_battery_level(
    NativePortType port_,
    int data,
  );

  external void wire__crate__api__hr_filtered_bpm(
    NativePortType port_,
    int data,
  );

  external void wire__crate__api__hr_raw_bpm(NativePortType port_, int data);

  external void wire__crate__api__hr_rmssd(NativePortType port_, int data);

  external void wire__crate__api__hr_timestamp(NativePortType port_, int data);

  external void wire__crate__api__hr_zone(
    NativePortType port_,
    int data,
    int max_hr,
  );

  external void wire__crate__api__init_logging(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__init_panic_handler(NativePortType port_);

  external void wire__crate__api__init_platform(NativePortType port_);

  external void wire__crate__api__list_plans(NativePortType port_);

  external void wire__crate__api__list_sessions(NativePortType port_);

  external void wire__crate__api__pause_workout(NativePortType port_);

  external void wire__crate__api__phase_progress_elapsed_secs(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__phase_progress_phase_index(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__phase_progress_phase_name(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__phase_progress_remaining_secs(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__phase_progress_target_zone(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__resume_workout(NativePortType port_);

  external void wire__crate__api__scan_devices(NativePortType port_);

  external void wire__crate__api__session_end_time(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_hr_sample_at(
    NativePortType port_,
    int session,
    JSAny index,
  );

  external void wire__crate__api__session_hr_samples_count(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_id(NativePortType port_, int session);

  external void wire__crate__api__session_phases_completed(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_plan_name(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_preview_avg_hr(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_preview_duration_secs(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_preview_id(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_preview_plan_name(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_preview_start_time(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_preview_status(
    NativePortType port_,
    int preview,
  );

  external void wire__crate__api__session_progress_current_bpm(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_current_phase(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_phase_progress(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_state(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_total_elapsed_secs(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_total_remaining_secs(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_progress_zone_status(
    NativePortType port_,
    int progress,
  );

  external void wire__crate__api__session_start_time(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_state_is_completed(
    NativePortType port_,
    int state,
  );

  external void wire__crate__api__session_state_is_paused(
    NativePortType port_,
    int state,
  );

  external void wire__crate__api__session_state_is_running(
    NativePortType port_,
    int state,
  );

  external void wire__crate__api__session_state_is_stopped(
    NativePortType port_,
    int state,
  );

  external void wire__crate__api__session_state_to_string(
    NativePortType port_,
    int state,
  );

  external void wire__crate__api__session_status(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_summary_avg_hr(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_summary_duration_secs(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_summary_max_hr(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_summary_min_hr(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__session_summary_time_in_zone(
    NativePortType port_,
    int session,
  );

  external void wire__crate__api__start_mock_mode(NativePortType port_);

  external void wire__crate__api__start_workout(
    NativePortType port_,
    String plan_name,
  );

  external void wire__crate__api__stop_workout(NativePortType port_);

  external void wire__crate__api__zone_status_is_in_zone(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__zone_status_is_too_high(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__zone_status_is_too_low(
    NativePortType port_,
    int status,
  );

  external void wire__crate__api__zone_status_to_string(
    NativePortType port_,
    int status,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiCompletedSession(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiConnectionStatus(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiPhaseProgress(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionProgress(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionState(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiSessionSummaryPreview(
    int ptr,
  );

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiZoneStatus(
    int ptr,
  );
}
