// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/heart_rate.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_ApiFilteredHeartRatePtr => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  ApiFilteredHeartRate
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    dynamic raw,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  dco_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    dynamic raw,
  );

  @protected
  RustStreamSink<LogMessage> dco_decode_StreamSink_log_message_Dco(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  DiscoveredDevice dco_decode_discovered_device(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<DiscoveredDevice> dco_decode_list_discovered_device(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  LogMessage dco_decode_log_message(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  Zone dco_decode_zone(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  ApiFilteredHeartRate
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ApiFilteredHeartRate>
  sse_decode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<LogMessage> sse_decode_StreamSink_log_message_Dco(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  DiscoveredDevice sse_decode_discovered_device(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<DiscoveredDevice> sse_decode_list_discovered_device(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  LogMessage sse_decode_log_message(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  Zone sse_decode_zone(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  String cst_encode_AnyhowException(AnyhowException raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String
  cst_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> raw,
  ) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData:
              dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_StreamSink_log_message_Dco(RustStreamSink<LogMessage> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_String(
      raw.setupAndSerialize(
        codec: DcoCodec(
          decodeSuccessData: dco_decode_log_message,
          decodeErrorData: dco_decode_AnyhowException,
        ),
      ),
    );
  }

  @protected
  String cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  double cst_encode_box_autoadd_f_64(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_f_64(raw);
  }

  @protected
  int cst_encode_box_autoadd_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_u_8(raw);
  }

  @protected
  JSAny cst_encode_discovered_device(DiscoveredDevice raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.id),
      cst_encode_opt_String(raw.name),
      cst_encode_i_16(raw.rssi),
    ].jsify()!;
  }

  @protected
  JSAny cst_encode_list_discovered_device(List<DiscoveredDevice> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.map(cst_encode_discovered_device).toList().jsify()!;
  }

  @protected
  JSAny cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.jsify()!;
  }

  @protected
  JSAny cst_encode_log_message(LogMessage raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return [
      cst_encode_String(raw.level),
      cst_encode_String(raw.target),
      cst_encode_u_64(raw.timestamp),
      cst_encode_String(raw.message),
    ].jsify()!;
  }

  @protected
  String? cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_String(raw);
  }

  @protected
  double? cst_encode_opt_box_autoadd_f_64(double? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_f_64(raw);
  }

  @protected
  int? cst_encode_opt_box_autoadd_u_8(int? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? null : cst_encode_box_autoadd_u_8(raw);
  }

  @protected
  JSAny cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  JSAny cst_encode_usize(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return castNativeBigInt(raw);
  }

  @protected
  int
  cst_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  int
  cst_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate raw,
  );

  @protected
  double cst_encode_f_64(double raw);

  @protected
  int cst_encode_i_16(int raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_u_16(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  int cst_encode_zone(Zone raw);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    ApiFilteredHeartRate self,
    SseSerializer serializer,
  );

  @protected
  void
  sse_encode_StreamSink_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate_Dco(
    RustStreamSink<ApiFilteredHeartRate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_log_message_Dco(
    RustStreamSink<LogMessage> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_discovered_device(
    DiscoveredDevice self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_discovered_device(
    List<DiscoveredDevice> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_log_message(LogMessage self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_zone(Zone self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);

  void wire__crate__api__connect_device(
    NativePortType port_,
    String device_id,
  ) => wasmModule.wire__crate__api__connect_device(port_, device_id);

  void wire__crate__api__create_hr_stream(NativePortType port_, String sink) =>
      wasmModule.wire__crate__api__create_hr_stream(port_, sink);

  void wire__crate__api__disconnect(NativePortType port_) =>
      wasmModule.wire__crate__api__disconnect(port_);

  void wire__crate__api__emit_hr_data(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__emit_hr_data(port_, data);

  void wire__crate__api__hr_battery_level(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_battery_level(port_, data);

  void wire__crate__api__hr_filtered_bpm(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_filtered_bpm(port_, data);

  void wire__crate__api__hr_raw_bpm(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_raw_bpm(port_, data);

  void wire__crate__api__hr_rmssd(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_rmssd(port_, data);

  void wire__crate__api__hr_timestamp(NativePortType port_, int data) =>
      wasmModule.wire__crate__api__hr_timestamp(port_, data);

  void wire__crate__api__hr_zone(NativePortType port_, int data, int max_hr) =>
      wasmModule.wire__crate__api__hr_zone(port_, data, max_hr);

  void wire__crate__api__init_logging(NativePortType port_, String sink) =>
      wasmModule.wire__crate__api__init_logging(port_, sink);

  void wire__crate__api__init_panic_handler(NativePortType port_) =>
      wasmModule.wire__crate__api__init_panic_handler(port_);

  void wire__crate__api__init_platform(NativePortType port_) =>
      wasmModule.wire__crate__api__init_platform(port_);

  void wire__crate__api__scan_devices(NativePortType port_) =>
      wasmModule.wire__crate__api__scan_devices(port_);

  void wire__crate__api__start_mock_mode(NativePortType port_) =>
      wasmModule.wire__crate__api__start_mock_mode(port_);

  void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  ) => wasmModule
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
        ptr,
      );

  void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  ) => wasmModule
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
        ptr,
      );
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {
  external void wire__crate__api__connect_device(
    NativePortType port_,
    String device_id,
  );

  external void wire__crate__api__create_hr_stream(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__disconnect(NativePortType port_);

  external void wire__crate__api__emit_hr_data(NativePortType port_, int data);

  external void wire__crate__api__hr_battery_level(
    NativePortType port_,
    int data,
  );

  external void wire__crate__api__hr_filtered_bpm(
    NativePortType port_,
    int data,
  );

  external void wire__crate__api__hr_raw_bpm(NativePortType port_, int data);

  external void wire__crate__api__hr_rmssd(NativePortType port_, int data);

  external void wire__crate__api__hr_timestamp(NativePortType port_, int data);

  external void wire__crate__api__hr_zone(
    NativePortType port_,
    int data,
    int max_hr,
  );

  external void wire__crate__api__init_logging(
    NativePortType port_,
    String sink,
  );

  external void wire__crate__api__init_panic_handler(NativePortType port_);

  external void wire__crate__api__init_platform(NativePortType port_);

  external void wire__crate__api__scan_devices(NativePortType port_);

  external void wire__crate__api__start_mock_mode(NativePortType port_);

  external void
  rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  );

  external void
  rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerApiFilteredHeartRate(
    int ptr,
  );
}
