// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A discovered BLE device during scanning.
///
/// This struct represents a device found during BLE scanning operations,
/// containing the minimal information needed to identify and connect to the device.
class DiscoveredDevice {
  /// Platform-specific device identifier.
  ///
  /// This is typically a UUID on iOS/macOS or a MAC address on Linux/Android.
  final String id;

  /// Advertised device name, if available.
  ///
  /// Not all devices advertise a name in their BLE advertisements.
  final String? name;

  /// Received Signal Strength Indicator in dBm.
  ///
  /// Typically ranges from -100 (weak) to -30 (strong). Used to estimate
  /// proximity and connection quality.
  final int rssi;

  const DiscoveredDevice({required this.id, this.name, required this.rssi});

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ rssi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredDevice &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          rssi == other.rssi;
}
