// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:uuid/uuid.dart';

/// A coaching directive — the output of the rule engine.
class Cue {
  final UuidValue id;
  final CueSource source;
  final String label;
  final String message;
  final CuePriority priority;
  final DateTime generatedAt;

  const Cue({
    required this.id,
    required this.source,
    required this.label,
    required this.message,
    required this.priority,
    required this.generatedAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      source.hashCode ^
      label.hashCode ^
      message.hashCode ^
      priority.hashCode ^
      generatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Cue &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          source == other.source &&
          label == other.label &&
          message == other.message &&
          priority == other.priority &&
          generatedAt == other.generatedAt;
}

enum CuePriority { low, normal, high, critical }

enum CueSource { targetZone, inactivity, overwork }
